-- Staging model for dbo.auth_users_plants
-- Generated by DataMigrate AI on 2025-12-05 14:46:23

{{ config(
    materialized='view',
    schema='staging'
) }}

WITH source AS (

    SELECT
        user_id,
    plant_id
    FROM {{ source('mssql_source', 'auth_users_plants') }}

),

staged AS (

    SELECT
        user_id,
    plant_id
    FROM source

)

SELECT * FROM staged
