-- Staging model for dbo.contacts
-- Generated by DataMigrate AI on 2025-12-05 14:46:23

{{ config(
    materialized='view',
    schema='staging'
) }}

WITH source AS (

    SELECT
        id,
    username,
    firstname,
    lastname,
    emailaddress,
    cellnumber,
    cellcarrierid,
    lang
    FROM {{ source('mssql_source', 'contacts') }}

),

staged AS (

    SELECT
        id,
    username,
    firstname,
    lastname,
    emailaddress,
    cellnumber,
    cellcarrierid,
    lang
    FROM source

)

SELECT * FROM staged
