-- Staging model for dbo.permanentnodes
-- Generated by DataMigrate AI on 2025-12-05 14:46:23

{{ config(
    materialized='view',
    schema='staging'
) }}

WITH source AS (

    SELECT
        id,
    name,
    uuid,
    editor,
    ipaddress,
    channelcount,
    osmajorrev,
    osminorrev,
    fwmajorrev,
    fwminorrev,
    fwbuildrev,
    devmajorrev,
    devminorrev,
    devicetype,
    imagefiles,
    deleted,
    connected,
    jsonstore,
    status,
    actual_flags,
    actual_readingretention,
    actual_wavretention,
    desired_flags,
    desired_readingretention,
    desired_wavretention,
    time_lastconnect,
    time_lastdisconnect,
    filetransferinprogress,
    filetransferinprogresspercent,
    filetransferinprogressname,
    filetransferoutprogress,
    filetransferoutprogresspercent,
    filetransferoutprogressname
    FROM {{ source('mssql_source', 'permanentnodes') }}

),

staged AS (

    SELECT
        id,
    name,
    uuid,
    editor,
    ipaddress,
    channelcount,
    osmajorrev,
    osminorrev,
    fwmajorrev,
    fwminorrev,
    fwbuildrev,
    devmajorrev,
    devminorrev,
    devicetype,
    imagefiles,
    deleted,
    connected,
    jsonstore,
    status,
    actual_flags,
    actual_readingretention,
    actual_wavretention,
    desired_flags,
    desired_readingretention,
    desired_wavretention,
    time_lastconnect,
    time_lastdisconnect,
    filetransferinprogress,
    filetransferinprogresspercent,
    filetransferinprogressname,
    filetransferoutprogress,
    filetransferoutprogresspercent,
    filetransferoutprogressname
    FROM source

)

SELECT * FROM staged
