-- Staging model for dbo.config
-- Generated by DataMigrate AI on 2025-12-05 14:46:23

{{ config(
    materialized='view',
    schema='staging'
) }}

WITH source AS (

    SELECT
        k,
    v
    FROM {{ source('mssql_source', 'config') }}

),

staged AS (

    SELECT
        k,
    v
    FROM source

)

SELECT * FROM staged
