-- Staging model for dbo.cellcarriers
-- Generated by DataMigrate AI on 2025-12-04 19:25:12

{{ config(
    materialized='view',
    schema='staging'
) }}

WITH source AS (

    SELECT
        id,
    carriername,
    carriercountry,
    carriernumberlength,
    carriermmsstring
    FROM {{ source('mssql_source', 'cellcarriers') }}

),

staged AS (

    SELECT
        id,
    carriername,
    carriercountry,
    carriernumberlength,
    carriermmsstring
    FROM source

)

SELECT * FROM staged
