-- Staging model for dbo.plants
-- Generated by DataMigrate AI on 2025-12-04 19:25:12

{{ config(
    materialized='view',
    schema='staging'
) }}

WITH source AS (

    SELECT
        id,
    softdeleted,
    imagefiles,
    plantname,
    plantorder,
    editor,
    updatedtime,
    updateduser,
    showtrash,
    comment,
    application_bearing_showtrash,
    application_electrical_showtrash,
    application_generic_showtrash,
    application_leak_showtrash,
    application_steam_showtrash,
    application_valve_showtrash,
    lists,
    altids
    FROM {{ source('mssql_source', 'plants') }}

),

staged AS (

    SELECT
        id,
    softdeleted,
    imagefiles,
    plantname,
    plantorder,
    editor,
    updatedtime,
    updateduser,
    showtrash,
    comment,
    application_bearing_showtrash,
    application_electrical_showtrash,
    application_generic_showtrash,
    application_leak_showtrash,
    application_steam_showtrash,
    application_valve_showtrash,
    lists,
    altids
    FROM source

)

SELECT * FROM staged
