-- Staging model for dbo.serverqueue
-- Generated by DataMigrate AI on 2025-12-04 19:25:12

{{ config(
    materialized='view',
    schema='staging'
) }}

WITH source AS (

    SELECT
        id,
    method,
    uuid,
    parameters,
    timestamp
    FROM {{ source('mssql_source', 'serverqueue') }}

),

staged AS (

    SELECT
        id,
    method,
    uuid,
    parameters,
    timestamp
    FROM source

)

SELECT * FROM staged
