-- Staging model for dbo.auth_users
-- Generated by DataMigrate AI on 2025-12-04 19:25:12

{{ config(
    materialized='view',
    schema='staging'
) }}

WITH source AS (

    SELECT
        user_id,
    admin,
    pw_hash,
    idp,
    idp_sub
    FROM {{ source('mssql_source', 'auth_users') }}

),

staged AS (

    SELECT
        user_id,
    admin,
    pw_hash,
    idp,
    idp_sub
    FROM source

)

SELECT * FROM staged
