-- Staging model for dbo.files
-- Generated by DataMigrate AI on 2025-12-04 19:25:12

{{ config(
    materialized='view',
    schema='staging'
) }}

WITH source AS (

    SELECT
        name,
    datestamp,
    data,
    fmode,
    fdata,
    fid
    FROM {{ source('mssql_source', 'files') }}

),

staged AS (

    SELECT
        name,
    datestamp,
    data,
    fmode,
    fdata,
    fid
    FROM source

)

SELECT * FROM staged
