"""
Lightweight Chat API - Standalone service for AI Support Chat

This is a minimal API that requires fastapi, uvicorn, and anthropic.
Run with: python -m uvicorn agents.chat_api:app --host 0.0.0.0 --port 8081 --reload
"""

import logging
import os
from pathlib import Path
from typing import List, Optional
from datetime import datetime

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

# Load .env files
try:
    from dotenv import load_dotenv
    # Try multiple .env locations
    env_paths = [
        Path(__file__).parent.parent / ".env",  # Project root
        Path(__file__).parent.parent / "backend" / ".env",  # Backend .env
        Path(__file__).parent / ".env",  # Agents folder
    ]
    for env_path in env_paths:
        if env_path.exists():
            load_dotenv(env_path)
            print(f"Loaded .env from: {env_path}")
except ImportError:
    pass  # dotenv not available

# Try to import anthropic
try:
    import anthropic
    ANTHROPIC_AVAILABLE = True
except ImportError:
    ANTHROPIC_AVAILABLE = False

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# Initialize Anthropic client
anthropic_client = None
ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY")

if ANTHROPIC_AVAILABLE and ANTHROPIC_API_KEY:
    anthropic_client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)
    logger.info("Claude AI initialized successfully")
else:
    if not ANTHROPIC_AVAILABLE:
        logger.warning("anthropic package not installed - using fallback responses")
    elif not ANTHROPIC_API_KEY:
        logger.warning("ANTHROPIC_API_KEY not set - using fallback responses")

# =============================================================================
# MODELS
# =============================================================================

class ChatMessage(BaseModel):
    """Chat message model"""
    role: str  # 'user' or 'assistant'
    content: str


class ChatRequest(BaseModel):
    """Chat request model"""
    message: str
    history: Optional[List[ChatMessage]] = None


class ChatResponse(BaseModel):
    """Chat response model"""
    response: str
    sources: Optional[List[str]] = None


# =============================================================================
# KNOWLEDGE BASE
# =============================================================================

KNOWLEDGE_BASE = {
    "migration": """DataMigrate AI helps you migrate MSSQL databases to dbt projects.
To create a migration:
1. Go to Migrations > New Migration
2. Configure your MSSQL connection (host, database, credentials)
3. Select tables to migrate
4. Choose your target warehouse (Snowflake, BigQuery, Fabric, etc.)
5. Configure dbt project settings
6. Start the migration - AI will generate models, tests, and documentation.""",

    "connection": """Database connections in DataMigrate AI:
- SQL Server Authentication: Use username/password
- Windows Authentication: Use trusted connection (no password needed)
- Default port: 1433
- Ensure SQL Server allows remote connections
- Check firewall rules for port access
Go to Settings > Connections to manage your database connections.""",

    "dbt": """dbt (data build tool) models generated by DataMigrate AI:
- Staging models: Raw data transformations
- Intermediate models: Business logic
- Tests: Data quality checks (unique, not_null, relationships)
- Documentation: Auto-generated from schema metadata
- Sources: YAML definitions for source tables
Target warehouses supported: Snowflake, BigQuery, Microsoft Fabric, Databricks, Redshift.""",

    "agent": """AI Agents available in DataMigrate AI:
1. DataPrep Agent: Data profiling, deduplication, outlier detection
2. ML Fine-Tuning Agent: Optimize transformations using machine learning
3. Data Quality Agent: Validate data integrity and quality
4. Documentation Agent: Generate comprehensive documentation
5. BI Agent: Business intelligence and analytics
Access agents from the Dashboard or navigate to /agents.""",

    "error": """Common troubleshooting steps:
1. Connection errors: Verify credentials, check network/firewall
2. Permission errors: Ensure user has SELECT permissions on tables
3. Timeout errors: Consider migrating fewer tables at once
4. Migration failures: Check logs in Migration Details view
For persistent issues, check the detailed logs or contact support.""",

    "default": """I'm your DataMigrate AI Support Assistant. I can help with:
- Creating and managing migrations
- Database connection configuration
- Understanding dbt models and transformations
- Using AI agents for data preparation
- Troubleshooting common issues
What would you like to know more about?"""
}


def get_ai_response(message: str, history: Optional[List[ChatMessage]] = None) -> str:
    """
    Generate AI response based on user message.
    Uses Claude AI if available, otherwise falls back to keyword matching.
    """
    # Try Claude AI first
    if anthropic_client:
        try:
            return get_claude_response(message, history)
        except Exception as e:
            logger.error(f"Claude API error: {e}")
            # Fall back to knowledge base on error

    # Fallback to keyword-based responses
    return get_fallback_response(message)


def get_claude_response(message: str, history: Optional[List[ChatMessage]] = None) -> str:
    """
    Get response from Claude AI with DataMigrate context.
    """
    system_prompt = """You are the AI Support Assistant for DataMigrate AI, a platform that helps migrate MSSQL databases to dbt projects.

Your knowledge includes:
- Creating and managing database migrations from MSSQL to dbt
- Configuring database connections (SQL Server, Windows Authentication)
- Understanding dbt models (staging, intermediate, tests, documentation)
- AI Agents: DataPrep Agent, ML Fine-Tuning Agent, Data Quality Agent, Documentation Agent, BI Agent
- Target warehouses: Snowflake, BigQuery, Microsoft Fabric, Databricks, Redshift
- Troubleshooting connection issues, permissions, and migration failures

Be helpful, concise, and friendly. Keep responses focused and practical.
If you don't know something specific about DataMigrate AI, provide general best practices for database migrations and dbt."""

    # Build messages for Claude
    messages = []

    # Add conversation history if provided
    if history:
        for msg in history:
            messages.append({
                "role": msg.role if msg.role in ["user", "assistant"] else "user",
                "content": msg.content
            })

    # Add current message
    messages.append({"role": "user", "content": message})

    logger.info(f"Sending request to Claude API...")

    response = anthropic_client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=1024,
        system=system_prompt,
        messages=messages
    )

    logger.info("Claude API responded successfully")
    return response.content[0].text


def get_fallback_response(message: str) -> str:
    """
    Fallback keyword-based response when Claude is unavailable.
    """
    lower_message = message.lower()

    # Keyword-based response selection
    if any(word in lower_message for word in ['migration', 'migrate', 'create', 'new migration']):
        return KNOWLEDGE_BASE["migration"]

    if any(word in lower_message for word in ['connect', 'connection', 'database', 'mssql', 'sql server', 'credentials']):
        return KNOWLEDGE_BASE["connection"]

    if any(word in lower_message for word in ['dbt', 'model', 'transformation', 'staging', 'warehouse']):
        return KNOWLEDGE_BASE["dbt"]

    if any(word in lower_message for word in ['agent', 'ai', 'dataprep', 'fine-tun', 'quality']):
        return KNOWLEDGE_BASE["agent"]

    if any(word in lower_message for word in ['error', 'fail', 'problem', 'issue', 'help', 'trouble']):
        return KNOWLEDGE_BASE["error"]

    return KNOWLEDGE_BASE["default"]


# =============================================================================
# FASTAPI APP
# =============================================================================

app = FastAPI(
    title="DataMigrate AI Chat Service",
    description="Lightweight AI support chat service",
    version="1.0.0"
)

# CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/health")
async def health_check():
    """Health check endpoint"""
    return {
        "status": "healthy",
        "service": "datamigrate-ai-chat",
        "claude_enabled": anthropic_client is not None,
        "timestamp": datetime.now().isoformat()
    }


@app.post("/chat", response_model=ChatResponse)
async def chat(request: ChatRequest):
    """
    AI Support Chat endpoint.
    Uses knowledge base for responses.
    """
    try:
        logger.info(f"Chat request: {request.message[:50]}...")
        response = get_ai_response(request.message, request.history)
        logger.info("Chat response generated successfully")
        return ChatResponse(response=response)
    except Exception as e:
        logger.error(f"Chat error: {e}")
        return ChatResponse(
            response="I apologize, but I'm having trouble processing your request. Please try again or check the Documentation section for help."
        )


# =============================================================================
# MAIN
# =============================================================================

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8081)
