-- Staging model for dbo.groups
-- Generated by DataMigrate AI on 2025-12-04 00:30:54

{{ config(
    materialized='view',
    schema='staging'
) }}

WITH source AS (

    SELECT
        id,
    softdeleted,
    imagefiles,
    plantid,
    groupname,
    grouptype,
    groupformat,
    groupdisplayfields,
    grouporder,
    hidealarms,
    alarmsonbottom,
    updatedtime,
    updateduser,
    showtrash,
    comment
    FROM {{ source('mssql_source', 'groups') }}

),

staged AS (

    SELECT
        id,
    softdeleted,
    imagefiles,
    plantid,
    groupname,
    grouptype,
    groupformat,
    groupdisplayfields,
    grouporder,
    hidealarms,
    alarmsonbottom,
    updatedtime,
    updateduser,
    showtrash,
    comment
    FROM source

)

SELECT * FROM staged
