-- Staging model for dbo.locations
-- Generated by DataMigrate AI on 2025-12-04 00:30:54

{{ config(
    materialized='view',
    schema='staging'
) }}

WITH source AS (

    SELECT
        id,
    softdeleted,
    imagefiles,
    groupid,
    locationorder,
    locationname,
    updatedtime,
    updateduser,
    linkednodes,
    showtrash,
    comment,
    ref_code,
    ref_equipmentinfo
    FROM {{ source('mssql_source', 'locations') }}

),

staged AS (

    SELECT
        id,
    softdeleted,
    imagefiles,
    groupid,
    locationorder,
    locationname,
    updatedtime,
    updateduser,
    linkednodes,
    showtrash,
    comment,
    ref_code,
    ref_equipmentinfo
    FROM source

)

SELECT * FROM staged
