-- Staging model for dbo.config_privileged
-- Generated by DataMigrate AI on 2025-12-04 00:30:54

{{ config(
    materialized='view',
    schema='staging'
) }}

WITH source AS (

    SELECT
        k,
    v
    FROM {{ source('mssql_source', 'config_privileged') }}

),

staged AS (

    SELECT
        k,
    v
    FROM source

)

SELECT * FROM staged
