-- Staging model for dbo.points
-- Generated by DataMigrate AI on 2025-12-04 00:30:54

{{ config(
    materialized='view',
    schema='staging'
) }}

WITH source AS (

    SELECT
        id,
    softdeleted,
    imagefiles,
    locationid,
    pointorder,
    pointname,
    monthrange,
    limitdisplaymonths,
    updatedtime,
    updateduser,
    showtrash,
    comment,
    ref_code,
    ref_equipmentinfo
    FROM {{ source('mssql_source', 'points') }}

),

staged AS (

    SELECT
        id,
    softdeleted,
    imagefiles,
    locationid,
    pointorder,
    pointname,
    monthrange,
    limitdisplaymonths,
    updatedtime,
    updateduser,
    showtrash,
    comment,
    ref_code,
    ref_equipmentinfo
    FROM source

)

SELECT * FROM staged
