-- Staging model for dbo.notification
-- Generated by DataMigrate AI on 2025-12-04 00:30:54

{{ config(
    materialized='view',
    schema='staging'
) }}

WITH source AS (

    SELECT
        id,
    contact_id,
    other_id,
    plant_id,
    group_id,
    location_id,
    point_id,
    notificationlevel,
    notificationlimit,
    notificationlimitinterval,
    jsonconfig,
    type,
    flag_all
    FROM {{ source('mssql_source', 'notification') }}

),

staged AS (

    SELECT
        id,
    contact_id,
    other_id,
    plant_id,
    group_id,
    location_id,
    point_id,
    notificationlevel,
    notificationlimit,
    notificationlimitinterval,
    jsonconfig,
    type,
    flag_all
    FROM source

)

SELECT * FROM staged
