-- Staging model for dbo.notificationhistory
-- Generated by DataMigrate AI on 2025-12-04 00:30:54

{{ config(
    materialized='view',
    schema='staging'
) }}

WITH source AS (

    SELECT
        id,
    notification_id,
    point_id,
    sent_time,
    sent
    FROM {{ source('mssql_source', 'notificationhistory') }}

),

staged AS (

    SELECT
        id,
    notification_id,
    point_id,
    sent_time,
    sent
    FROM source

)

SELECT * FROM staged
